vercel/swr-site

.nextra/layout.js
.nextra/search.js
.nextra/styles.css
.nextra/theme.js
nextra.config.js
package.json
pages/_app.js
pages/_document.js
pages/change-log.mdx
pages/docs/data-fetching.mdx
pages/docs/pagination.mdx
pages/docs/suspense.mdx
yarn.lock

- Fix a11y score on lighthouse
- use `next-google-fonts` to asynchronously load Inter
- Fix best practices score on lighthouse
- Defer/async the docsearch CSS and JS. Since the search is opened after first interaction, it can be delayed
- Add focus styles to sidebar, improve focus style of header links
- Add skip-nav to jump to main content
Todo:
Before:
After:

A11y and performance improvements

---

.nextra/docsearch.js
.nextra/styles.css
pages/docs/meta.json
pages/docs/pagination.mdx
pages/examples/infinite-loading.js
pages/examples/meta.json

This new API was already released at `swr@0.3.0`, this PR adds the corresponding docs and example of it.
https://swr-site-git-add-swr-infinite.vercel.vercel.app/docs/pagination
https://swr-site-git-add-swr-infinite.vercel.vercel.app/examples/infinite-loading

Add docs and example for useSWRInfinite

---

pages/docs/global-configuration.md

Fetch takes only 2 arguments, spread operator on args will result in a typescript error. This commit makes it clear and strict that fetch takes an `input` and an `init` object.
More information here: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
Related error: `Expected 1-2 arguments, but got 0 or more.ts(2556)`

fix fetch params

---

pages/docs/error-handling.mdx

In https://swr.vercel.app/docs/options#options the property is called `config`, and that is consistent with other callbacks SWR receive.

Rename option to config

---

pages/docs/error-handling.mdx

As described here: https://github.com/vercel/swr/issues/215 and later fixed here: https://github.com/vercel/swr/pull/216
I discovered this after getting confused about whether to await before returning or not.

Update to be consistent with other examples

---

theme.config.js

Avoid the below warning message that exists on the terminal.

Correct event onload naming

---

pages/docs/data-fetching.mdx

ref. https://github.com/vercel/swr/pull/904
I've replaced a Graph.Cool endpoint with a fake GraphQL endpoint.

use a fake GraphQL endpoint instead of graph.cool

---

pages/docs/suspense.mdx

The current callout for suspense in dark mode is hard to read.
https://swr.vercel.app/docs/suspense
Current:
After:

fix: color contrast of a callout for suspense in the dark mode

---

pages/docs/suspense.mdx

ref. https://github.com/vercel/swr/pull/898/files#r559133243
This adds a warning for changing the `suspense` option in the lifecycle.

docs: add a warning for chaning the suspense option in the lifecycle

---

pages/docs/pagination.mdx

`useSWRInfinite` returns `error` and `isValidating`, but they are not documented, so I've added them into the document.

docs: add missing return values of useSWRInfinite

---

pages/docs/arguments.en-US.md

Not terribly important, but the words "because" and "so" have the same function in this sentence, so using both is redundant and less clear.
- Before:
- Because the identifier (also the cache key) of the data is `'/api/user'`, **so** even if `token` changes, SWR will still use the same key and return the wrong data.
- After:
- Because the identifier (also the cache key) of the data is `'/api/user'`, even if `token` changes, SWR will still use the same key and return the wrong data.

Improve grammar in "Arguments"

---

pages/advanced/performance.en-US.mdx
pages/advanced/performance.zh-CN.mdx

With https://github.com/vercel/swr/pull/967, `isValidating` will be `true` by default in the first render. This reduces the overall re-renders.

Update performance page

---

components/features.js
next.config.js
pages/advanced/meta.es-ES.json
pages/advanced/performance.es-ES.mdx
pages/change-log.es-ES.mdx
pages/docs/arguments.es-ES.md
pages/docs/conditional-fetching.es-ES.md
pages/docs/data-fetching.es-ES.mdx
pages/docs/error-handling.es-ES.mdx
pages/docs/global-configuration.es-ES.md
pages/docs/meta.es-ES.json
pages/docs/mutation.es-ES.md
pages/docs/options.es-ES.mdx
pages/docs/pagination.es-ES.mdx
pages/docs/prefetching.es-ES.md
pages/docs/revalidation.es-ES.mdx
pages/docs/suspense.es-ES.mdx
pages/docs/with-nextjs.es-ES.md
pages/examples/auth.es-ES.mdx
pages/examples/basic.es-ES.mdx
pages/examples/error-handling.es-ES.mdx
pages/examples/infinite-loading.es-ES.mdx
pages/examples/meta.es-ES.json
pages/getting-started.es-ES.mdx
pages/index.es-ES.mdx
pages/meta.es-ES.json
theme.config.js

This PR focuses on Spanish language support to the site. Closes #95
Spanish is ranked **number 2** of the [10 most spoken languages](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers) in the world. 
SWR was downloaded [1.3 million](https://yarnpkg.com/package/swr) according to yarn data in the last month, a large part of that percentage are people who speak Spanish. Although I share the idea that English is important for any developer, it is good to have the option.
- feat: added support for Spanish language
- doc(language): now the footer text is on Spanish
- docs(language): I18: Snpanish
- docs(language): Added metadata Spanish
- docs(language): I18 index spanish page
- docs(language): I18 Getting started to spanish
- docs(language): I18 Change log page to …

I18n: Spanish

---

pages/advanced/performance.es-ES.mdx
pages/change-log.es-ES.mdx
theme.config.js

This PR focuses on improves Spanish translated, and opt use of the impersonal language. Thank You, @ernestd for the observation on typos mentioned #96.
I took care of the little problem of the [duplicated title on the home page](https://github.com/vercel/swr-site/issues/82). Basically, opt to leave the value of `titleSuffix` with an empty string, my intention was to omit the property but the default value **nextra** is used title home page.
```js
export default {
titleSuffix: ' '
...
}
```
Closes #82

Improves Spanish translated and little more 

---

pages/advanced/cache.en-US.md

With this PR we try to improve the Custom Cache docs structure. In the future we might want to introduce a "Examples" section for various use cases and examples of the new cache API (and cross-reference to other pages), see also #108.

Some touches to the Custom Cache docs

---

pages/docs/advanced/cache.en-US.mdx

I noticed the cache name was changed to `swr-cache` but only on `getItem` so I reverted to `app-cache`.

Fix cache name

---

pages/docs/advanced/cache.en-US.mdx

A small typo I noticed while reading the docs:
`wrap you application` > `wrap your application`

fix typo in cache.en-US.mdx

---

pages/docs/arguments.en-US.md
pages/docs/arguments.es-ES.md
pages/docs/arguments.ja.md
pages/docs/arguments.ko.md
pages/docs/arguments.ru.md

It's now safe to pass objects as the key thanks to hashing.

1.1.0: update the docs of object keys

---

pages/docs/pagination.en-US.mdx
pages/docs/pagination.es-ES.mdx
pages/docs/pagination.ja.mdx
pages/docs/pagination.ko.mdx
pages/docs/pagination.ru.mdx
pages/docs/pagination.zh-CN.mdx

This adds the `revalidateFirstPage` option in the document, which is added by https://github.com/vercel/swr/pull/1538.

add the revalidateFirstPage option

---

pages/docs/middleware.en-US.md
pages/docs/middleware.ja.md
pages/docs/middleware.ko.md
pages/docs/middleware.ru.md
pages/docs/middleware.zh-CN.md

Add the same callouts to the middleware section which are used in the arguments section.

update middleware docs after the new 1.1.0 release

---

pages/docs/options.en-US.mdx
pages/docs/options.es-ES.mdx
pages/docs/options.ja.mdx
pages/docs/options.ko.mdx
pages/docs/options.ru.mdx
pages/docs/options.zh-CN.mdx

Related to https://github.com/vercel/swr/pull/1690
`refreshInterval` now allows passing either a number or a function as an interval. 
I don't know how to organize this because it is the only option that has multiple forms. I'll update other languages after the English version is approved.

docs: refreshInterval as a function

---

pages/docs/typescript.en-US.mdx

Under the TypeScript docs, [`/docs/typescript`](https://swr.vercel.app/docs/typescript), I came across a couple of typos for "specify(ing)", which this PR addresses:
| Current (PROD) | After (Corrections) | 
|---|---|
| <img width="1276" alt="Screen Shot 2022-01-08 at 3 46 17 PM" src="https://user-images.githubusercontent.com/39503964/148663814-4eecdc6d-b86c-4163-a751-b5f13396be84.png"> | <img width="1319" alt="Screen Shot 2022-01-08 at 3 44 47 PM" src="https://user-images.githubusercontent.com/39503964/148663821-1bf78b07-9804-4e20-acf8-e45340d89d60.png"> | 
Similarly, I would like to suggest the renaming of the SWR site's default branch from `master` to `main`, which I did on my forked version. More context here on this rename proposal, https://github.com/github/renaming. 
- If there is …

doc: correcting a couple of typos in TypeScript section

---

README.md
package.json
pnpm-lock.yaml
styles.css

A locale related bug and some CSS issues were fixed in the new version, as well as a performance boost. Also we now recommend `pnpm` over `yarn` for Nextra projects at this moment.
Closes #211.

Bump Nextra version and update readme

---

pages/docs/global-configuration.en-US.md

The cache link is broken on this page. This change references the updated cache docs.

Fix cache link

---

pages/docs/mutation.en-US.md

The current cache provider link is broken and needs to be updated to the new link.

Update cache documentation link

---

pages/docs/meta.en-US.json
pages/docs/meta.es-ES.json
pages/docs/meta.ja.json
pages/docs/meta.ko.json
pages/docs/meta.ru.json
pages/docs/meta.zh-CN.json

This is petty, I know — I noticed that in the live site TypeScript is incorrectly capitalized as 'Typescript' in the sidebar. This PR fixes all instances of this capitalization. It's very minor but it still bugged me enough to submit this PR. Thanks for your consideration! 😄

Capitalize TypeScript in translations

---

pages/docs/global-configuration.ko.md

I think "Cache document" has been moved from "/docs/cache" to "/docs/advanced/cache", so I've updated the link.

doc: Update link of a moved document

---

pages/docs/getting-started.es-ES.mdx

I have detected a typo on the word "suspeción" (It doesn't exist) and changed it to "suspensión". I think that's the word that was meant to be used.

Fix Spanish documentation typo on the Getting started page

---

pages/docs/typescript.en-US.mdx
pages/docs/typescript.es-ES.mdx
pages/docs/typescript.ja.mdx
pages/docs/typescript.ko.mdx
pages/docs/typescript.ru.mdx
pages/docs/typescript.zh-CN.mdx

fixes #258 
The import statement should be a default import instead of a named import.

fix: import statement in the TypeScript example

---

pages/docs/mutation.en-US.md

The optimistic update example needs the key passed as the first param of the (config) mutate function, or use the bound mutate function (as it is done in the [example](https://codesandbox.io/embed/swr-basic-forked-k5hps?fontsize=14&hidenavigation=1&theme=dark)). 
Note: I checked the other language files but they don't seem to have this example.

Fix optimistic update example

---

pages/docs/global-configuration.ja.md

This PR is fix broken link to cache.
in global-configuration.ja.md

docs: fix broken link to cache

---

pages/docs/mutation.es-ES.md
pages/docs/mutation.ko.md

I tried to update the mutate page, but I've found that the mutate pages of some languages are not synced. So I've synced them before updating the page.

docs: sync optimistic update docs of some languages

---

pages/docs/typescript.en-US.mdx
pages/docs/typescript.es-ES.mdx
pages/docs/typescript.ja.mdx
pages/docs/typescript.ko.mdx
pages/docs/typescript.ru.mdx
pages/docs/typescript.zh-CN.mdx

Add example how to specify the `useSWR` error type in TypeScript. Fix also typo in swr/inifite.

doc: Add TypeScript error type info

---

pages/docs/mutation.en-US.md
pages/docs/mutation.es-ES.md
pages/docs/mutation.ja.md
pages/docs/mutation.ko.md
pages/docs/mutation.pt-BR.md
pages/docs/mutation.ru.md
pages/docs/mutation.zh-CN.md

This adds documentation of https://github.com/vercel/swr/pull/1861, which is a part of v2 documentation.
Personally, I'd like to improve the structure of mutation docs, and I've already made a PR for it.
https://github.com/vercel/swr-site/pull/324

docs: optimisticData can accept a function in v2

---

pages/docs/typescript.ja.mdx

I translated into Japanese in TypeScript page which hadn't translated into Japanese or which had seemed to be not properly translated.

doc: translate typescript page into Japanese

---

pages/docs/global-configuration.en-US.md
pages/docs/global-configuration.es-ES.md
pages/docs/global-configuration.ja.md
pages/docs/global-configuration.ko.md
pages/docs/global-configuration.pt-BR.md
pages/docs/global-configuration.ru.md
pages/docs/global-configuration.zh-CN.md

This adds documentation for a pattern of nesting configurations with `SWRConfig`, which also includes supporting a function as the SWRConfig value added in v2.
https://github.com/vercel/swr/pull/2024

docs: SWRConfig value as a function

---

pages/docs/arguments.en-US.md
pages/docs/arguments.es-ES.md
pages/docs/arguments.ja.md
pages/docs/arguments.ko.md
pages/docs/arguments.pt-BR.md
pages/docs/arguments.ru.md
pages/docs/arguments.zh-CN.md
pages/docs/mutation.zh-CN.md
pages/docs/typescript.en-US.mdx
pages/docs/typescript.es-ES.mdx
pages/docs/typescript.ja.mdx
pages/docs/typescript.ko.mdx
pages/docs/typescript.pt-BR.mdx
pages/docs/typescript.ru.mdx
pages/docs/typescript.zh-CN.mdx

This is an update for https://github.com/vercel/swr/pull/1864.
The target branch of this PR is `v2`.
This PR has many diffs in `pt-BR` pages, which is the same issue with #324...

Fetcher no longer accepts multiple arguments in v2

---

pages/docs/prefetching.en-US.md
pages/docs/prefetching.es-ES.md
pages/docs/prefetching.ja.md
pages/docs/prefetching.ko.md
pages/docs/prefetching.pt-BR.md
pages/docs/prefetching.ru.md
pages/docs/prefetching.zh-CN.md

This adds an example  for the `preload` API in effects, which @huozhi mentioned in https://github.com/vercel/swr-site/pull/336#discussion_r958432267.

docs: add an example for preload in effect

---

pages/docs/mutation.en-US.md

This adds the documentation for `useSWRMutation`.
I've refined the structure of the mutation page to align with other pages.
I've also added the use case of using `useSWRMutation` for loading data.

add documentations for useSWRMutation

---

pages/docs/mutation.en-US.md
pages/docs/mutation.es-ES.md
pages/docs/mutation.ja.md
pages/docs/mutation.ko.md
pages/docs/mutation.pt-BR.md
pages/docs/mutation.ru.md
pages/docs/mutation.zh-CN.md

This is a follow-up PR of #348, which applies the updates to other languages.
I've also moved a section for return values of `mutate` into `API` section, which makes it easy to find out the return value of `mutate`. https://github.com/vercel/swr-site/commit/9ed2b80712172bc7f40c926d673578ea07184590

sync and refine mutate page

---

pages/docs/mutation.en-US.md
pages/docs/mutation.es-ES.md
pages/docs/mutation.ja.md
pages/docs/mutation.ko.md
pages/docs/mutation.pt-BR.md
pages/docs/mutation.ru.md
pages/docs/mutation.zh-CN.md

This makes explicit the location where `mutate` can be imported. I've also mentioned a bound mutate function on top of the page.

make explicit the location of mutate

---

pages/blog/swr-v2.en-US.mdx
pages/blog/swr-v2.es-ES.mdx
pages/blog/swr-v2.ja.mdx
pages/blog/swr-v2.ko.mdx
pages/blog/swr-v2.pt-BR.mdx
pages/blog/swr-v2.ru.mdx
pages/blog/swr-v2.zh-CN.mdx
pages/docs/mutation.en-US.md
pages/docs/mutation.es-ES.md
pages/docs/mutation.ja.md
pages/docs/mutation.ko.md
pages/docs/mutation.pt-BR.md
pages/docs/mutation.ru.md
pages/docs/mutation.zh-CN.md

fix: typos in v2 docs

---

pages/blog/meta.ja.json
pages/blog/swr-v2.ja.mdx

I'll work on translating other pages updated in v2 later.
It's ok to merge this after releasing the v2 blog.

docs: translate v2 blog into Japanese

---

pages/docs/mutation.en-US.md
pages/docs/mutation.es-ES.md
pages/docs/mutation.ja.md
pages/docs/mutation.ko.md
pages/docs/mutation.pt-BR.md
pages/docs/mutation.ru.md
pages/docs/mutation.zh-CN.md

Fixes a typo in a variable name in the documentation for `mutation`

fix variable typo in mutation documentation

---

pages/docs/prefetching.en-US.md
pages/docs/prefetching.es-ES.md
pages/docs/prefetching.ja.md
pages/docs/prefetching.ko.md
pages/docs/prefetching.pt-BR.md
pages/docs/prefetching.ru.md
pages/docs/prefetching.zh-CN.md

In the react example, the dependency array passed to the useEffect had useId instead of userId .

Preload docs - Correction to code.

---

pages/docs/advanced/cache.en-US.mdx
pages/docs/advanced/cache.ja.mdx
pages/docs/advanced/cache.ko.mdx
pages/docs/advanced/cache.pt-BR.mdx
pages/docs/advanced/cache.ru.mdx
pages/docs/advanced/cache.zh-CN.mdx

[This code example](https://swr.vercel.app/ko/docs/advanced/cache#modify-the-cache-data) shows how to clear cache with the ```mutate``` function.
However, The ```cache``` object is deconstructed instead of the ```mutate``` function.
So It have to replace with the ```mutate``` function instead of the ```cache``` object
***This PR changed all languages.***

docs: fix hooks destructure typo error in clear all cache code examples

---

pages/docs/arguments.en-US.md

"In the above example, `url` and `token` are both _tight_ to the cache key." 
"In the above example, `url` and `token` are both _tied_ to the cache key."
```diff
- tight
+ tied
```

[swr-Docs: Argument] Typo fix

---

pages/docs/pagination.en-US.mdx
pages/docs/pagination.es-ES.mdx
pages/docs/pagination.ja.mdx
pages/docs/pagination.ko.mdx
pages/docs/pagination.pt-BR.mdx
pages/docs/pagination.ru.mdx
pages/docs/pagination.zh-CN.mdx

- fix typo in example code
- please check this at https://swr.vercel.app/docs/pagination#global-mutate-with-useswrinfinite
- and all of docs using this example code with typo

docs: fix typo swr/infinte -> swr/infinite

---

theme.config.js

https://ogp.me/
https://developers.facebook.com/docs/sharing/webmasters
Following open graph protocol, use 'property' attribute
[result of sharing debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fswr.vercel.app%2F)

fix: change attribute name of open graph

---

pages/docs/global-configuration.ja.mdx

A typo in the Japanese documentation has been corrected.

docs: fix typo

---

pages/docs/api.ja.mdx

A translation omission in the Japanese document has been corrected.

docs: fix translation omissions

---

pages/index.en-US.mdx
pages/index.es-ES.mdx
pages/index.ja.mdx
pages/index.ko.mdx
pages/index.pt-BR.mdx
pages/index.ru.mdx
pages/index.zh-CN.mdx

The index page contains a link for Blog.  When clicking on the link it directs the user to [Announcing SWR 1.0](https://swr.vercel.app/blog/swr-v1), the first blog post.  As there are now two blog posts on the site, I changed the Blog link on the index page to direct the user to [SWR Blog](https://swr.vercel.app/blog) instead.  This allows the user see all of the blog posts instead of giving the false impression that there is only one.
* Replace `/blog/swr-v1` with `/blog` in all `pages/index*` mdx files
* Removed empty new line in `index.en-US.mdx`
Current - Hovering Blog shows link to `localhost:3000/blog/swr-v1` - (Highlighted with red square)
Update - Hovering Blog shows link to `localhost:3000/blog` - (Highlighted with red square)

fix: Replace `/blog/swr-v1` with `/blog` on index pages

---

pages/docs/typescript.en-US.mdx

Updated two minor typo errors in the English docs for typescript.

Minor typo fixes in typescript Docs

---

pages/docs/getting-started.pt-BR.mdx

it was "veja maias exemplos", and the correct is "veja mais exemplos"

docs: fixed misspell in example section

---

pages/index.en-US.mdx
pages/index.es-ES.mdx
pages/index.fr-FR.mdx
pages/index.ja.mdx
pages/index.ko.mdx
pages/index.pt-BR.mdx
pages/index.ru.mdx
pages/index.zh-CN.mdx

I think this can be minor changes... but I think this is useless classNames solved by using `gap-2` to parent `p` tag.

chore: Update useless className using gap-2

---

pages/index.en-US.mdx
pages/index.ko.mdx

I Update return value description in [Index page](https://swr.vercel.app/)
I think this example using `data`, `isLoading` and `error`. 
However, `isLoading` is missing from the description.
So I add isLoading in en-US and ko.
As far as I know, the `useSWR` has other return values except for `data`, `isLoading`, and `error`, 
but the description says that **only 2 values are returned**. 
How about hanging the `read more link` for the other return values??

docs: Update useSWR return value descriptions

---

pages/docs/suspense.pt-BR.mdx

Fix typo in portuguese version of Suspense page.

fix: typo in portuguese version of Suspense page

---

pages/docs/with-nextjs.en-US.mdx
pages/docs/with-nextjs.es-ES.mdx
pages/docs/with-nextjs.fr-FR.mdx
pages/docs/with-nextjs.ja.mdx
pages/docs/with-nextjs.ko.mdx
pages/docs/with-nextjs.pt-BR.mdx
pages/docs/with-nextjs.ru.mdx
pages/docs/with-nextjs.zh-CN.mdx

- add missing 'function' on example code.
- Add missing 'function' on example code. 
- https://swr.vercel.app/docs/with-nextjs
- BEFORE
```tsx filename="app/page.tsx" highlight={1} copy
'use client'
import useSWR from 'swr'
export default Page() {  //👈missing 'function' here
const { data } = useSWR('/api/user', fetcher)
return <h1>{data.name}</h1>
}
```
- AFTER
```tsx filename="app/page.tsx" highlight={1} copy
'use client'
import useSWR from 'swr'
export default function Page() {
const { data } = useSWR('/api/user', fetcher)
return <h1>{data.name}</h1>
}
```

docs: fix error(typo) on `with-nextjs page` example code

---

pages/docs/advanced/devtools.zh-CN.mdx
pages/docs/api.zh-CN.mdx
pages/docs/pagination.zh-CN.mdx
pages/docs/prefetching.zh-CN.mdx
pages/docs/revalidation.zh-CN.mdx

docs: update simplified Chinese translations

---

pages/docs/advanced/devtools.ko.mdx
pages/docs/advanced/understanding.ko.mdx
pages/docs/pagination.ko.mdx
pages/docs/revalidation.ko.mdx
pages/docs/with-nextjs.ko.mdx

Hi, Thanks for making great library. There were some Korean translations missing, so I added them
- Add ko translations for `with-nextjs.ko.mdx`, `advanced/understanding.ko.mdx`, `advanced/devtools.ko.mdx`
- Update ko translations for `pagination.ko.mdx`, `revalidation.ko.mdx`

docs: Add ko translations for missing pages and paragraphs

---

pages/docs/suspense.en-US.mdx
pages/docs/suspense.es-ES.mdx
pages/docs/suspense.fr-FR.mdx
pages/docs/suspense.ja.mdx
pages/docs/suspense.ko.mdx
pages/docs/suspense.pt-BR.mdx
pages/docs/suspense.ru.mdx
pages/docs/suspense.zh-CN.mdx

Remove the suspense callout since its already stable in React 19 and useSWR utilizes [use](https://react.dev/reference/react/use) under the hood.

Remove suspense callout
