vercel/swr-site

pages/index.js
Nothing big, just something that didn't feel right when reading through the page earlier today.
=> change wording for refetch on interval figure

pages/index.js
https://twitter.com/joshleong/status/1256019423489482752
=> Fix GraphQL example

README.md
Merge this once we have github.com/vercel available.
=> [Pre-emptive] ZEIT → Vercel

docs/index.mdx
Instead of proxying through Cloudinary
=> Serve videos from GitHub repo

.nextra/docsearch.js, .nextra/layout.js
=> Add back DocSearch

pages/docs/arguments.md
Hello Vercel 👋 
Not sure I'm right on this (just starting to learn Next.js and SWR), but the `identifier` looks incorrect to me.
Do not hesitate to comment/close this PR if I'm wrong
Have a nice day !
=> Fix incorrect identifier

pages/docs/with-nextjs.md
Suggestion from @chibicode, that we need to mention data fetching in `getStaticProps` happens in the server side.
=> Add note to mention data fetching environments

pages/docs/error-handling.mdx, pages/docs/meta.json, pages/examples/error-handling.js
This PR adds the docs of Error Handling, including 3 sections:
- Status Code and Error Object
- Error Retry
- Global Error Report
https://swr-site-git-add-error-handling.vercel.now.sh/docs/error-handling
=> Add docs of SWR Error Handling

pages/docs/pagination.mdx
Fixed a small typo found in one of the examples.
=> Fix typo on pagination page

package.json, yarn.lock
`nextra-theme-docs@0.2.0` improves font loading speed and fixes some minor style issues:
=> Upgrade to Next.js 10 and Nextra theme

pages/docs/with-nextjs.md
Resolve https://github.com/vercel/swr/issues/762
=> fix: typo Props -> Posts

pages/index.mdx
This PR updates updates 'JAMstack' => 'Jamstack' on the Overview page.
=> Update 'JAMstack' => 'Jamstack'

components/features.js
Update 'JAMstack' => 'Jamstack' in features.js
=> Update 'JAMstack' => 'Jamstack' in features.js

pages/docs/mutation.md
Make the explanation of `mutate` code example follow the same order as the code above it, it could be confusing that the order of events differs compared to the code.
=> Update mutation.md code explanation

pages/docs/options.mdx
document https://github.com/vercel/swr/pull/845
=> docs: add field for config.isPaused

package.json, yarn.lock
=> Upgrade theme

pages/docs/error-handling.en-US.mdx, pages/docs/error-handling.zh-CN.mdx
Resolves https://github.com/vercel/swr/issues/1123
=> fix: onErrorRetry example

pages/docs/data-fetching.zh-CN.mdx
Fix code example in data-fetching.zh-CN.mdx
=> Fix code example in data-fetching.zh-CN.mdx

README.md
This PR focuses on improving the credits in  readme file also I was added my username for last contribution translated of site to Spanish.
- docs(readme): Improving credits and add one more.
=> Improving credits and add one more

pages/docs/mutation.en-US.md
closes the report that I opened in the swr repo https://github.com/vercel/swr/issues/1214
=> fix(mutation): clarify error behaviour

pages/advanced/cache.zh-CN.md, pages/advanced/meta.zh-CN.json
=> Translate cache.zh-CN.md

pages/advanced/cache.en-US.md, pages/advanced/cache.zh-CN.md
* add exampel section for local storage state sync
* add Chinese translation
related to https://github.com/vercel/swr/issues/973
=> docs: add local storage example

pages/advanced/cache.ja.md, pages/docs/with-nextjs.ja.md
Supported the following commit updates.
- b34a074b45e116f26742507f185e8dde12bbae37
- bceef747213495b3d0ddcce82799d82bb94afefe
=> Updated Japanese translation

pages/docs/with-nextjs.es-ES.md, pages/docs/with-nextjs.zh-CN.md
Sync [`bceef74`](https://github.com/vercel/swr-site/commit/bceef747213495b3d0ddcce82799d82bb94afefe)
=> Update with-nextjs.zh-CN.md and with-nextjs.es-ES.md

pages/advanced/cache.en-US.md, pages/advanced/cache.ja.md, pages/advanced/cache.zh-CN.md
=> Use JSON.stringify/parse for caching to localStorage

next.config.js
Make it easier for users to visit docs page
=> Redirect docs to getting started

pages/docs/advanced/cache.en-US.md, pages/docs/advanced/cache.zh-CN.md
Related to https://github.com/vercel/swr/issues/781
=> Add reset cache while testing example

pages/docs/with-nextjs.ko.md
Fix text that is not bolded properly.
[Before]
**정적 생성(SSG)**과 **서버 사이드 렌더링(SSR)**. 
[After]
**정적 생성(SSG)** 과 **서버 사이드 렌더링(SSR)**.
=> Fix: typo in with-nextjs.ko.md

pages/docs/advanced/cache.en-US.mdx
Looks like muscle memory from typing 'react' so much :)
=> Fixes re-created typo

pages/docs/options.en-US.mdx
_This is a quick fix. Will refine this entire page later._
=> Add notes to several interval options to mention the units as ms

pages/docs/advanced/cache.ja.mdx
fix cache key name of localStorageProvider code example
=> fix: cache.ja.mdx

pages/docs/options.en-US.mdx, pages/docs/options.es-ES.mdx, pages/docs/options.ja.mdx, pages/docs/options.ko.mdx, pages/docs/options.ru.mdx, pages/docs/options.zh-CN.mdx
Refs: https://github.com/vercel/swr-site/pull/174#issuecomment-956166833
=> Remove options.fetcher default value

pages/docs/arguments.ja.md, pages/docs/middleware.ja.md, pages/docs/options.ja.mdx, pages/docs/pagination.ja.mdx
Translated the part updated in SWR v1.1.0 into Japanese.
=> Update Japanese translation for SWR v1.1.0

pages/docs/meta.en-US.json, pages/docs/meta.es-ES.json, pages/docs/meta.ja.json, pages/docs/meta.ko.json, pages/docs/meta.ru.json, pages/docs/meta.zh-CN.json, pages/docs/typescript.en-US.mdx
Basci usage with typescript
cc @promer94 as the contributor of swr on typescript improvement
=> Use with Typescript

pages/docs/middleware.en-US.md
https://github.com/vercel/swr/discussions/1739
=> Add typescript example (vercel/swr discussion#1739)

pages/docs/middleware.en-US.md, pages/docs/middleware.ja.md, pages/docs/middleware.ko.md, pages/docs/middleware.ru.md, pages/docs/middleware.zh-CN.md
=> Update ts link for middleware

package.json, pages/docs/options.es-ES.mdx, pnpm-lock.yaml, theme.config.js
- A bug when the browser preferred language isn't `en-US`
- Wrong project link
=> Bug fixes for the new theme

package.json, pnpm-lock.yaml, theme.config.js
Multiple bugs related to i18n were fixed in this new version.
=> Upgrade Nextra

package.json, pnpm-lock.yaml
https://github.com/shuding/nextra/pull/340
=> Group search results

package.json, pnpm-lock.yaml
This Nextra upgrade should fix the 404 error for the data file. Also it improves the sorting a bit to present those exact matches in page title first.
=> Fix search indexing

pages/index.en-US.mdx, pages/index.es-ES.mdx, pages/index.ja.mdx, pages/index.ko.mdx, pages/index.ru.mdx, pages/index.zh-CN.mdx
A horizontal scroll bar is appearing in certain viewports.
=> Remove horizontal scroll bar bug.

pages/docs/arguments.es-ES.md
=> correct word

pages/docs/with-nextjs.ko.md
add translation for with-nextjs.ko.md
with-nextjs 하단에 해석이 안되어 있던 부분 해석 추가했습니다.
=> doc: Update Korean translation

pages/docs/options.en-US.mdx, pages/docs/options.es-ES.mdx, pages/docs/options.ja.mdx, pages/docs/options.ko.mdx, pages/docs/options.ru.mdx, pages/docs/options.zh-CN.mdx
We are no longer using dequal for this purpose.
=> Update docs of the comparison function

pages/docs/typescript.en-US.mdx
Hello. Found a typo while reading your docs. You are amazing anyway 👍
=> fix typo in docs

theme.config.js
Adding translations for Powered by Vercel footer label.
=> Add translations for Powered by Vercel in Brazilian Portuguese

pages/blog/swr-v1.pt-BR.mdx, pages/docs/advanced/cache.pt-BR.mdx, pages/docs/advanced/meta.pt-BR.json, pages/docs/advanced/performance.pt-BR.mdx, pages/docs/advanced/react-native.pt-BR.mdx, pages/docs/arguments.pt-BR.md, pages/docs/data-fetching.pt-BR.mdx, pages/docs/error-handling.pt-BR.mdx, pages/docs/getting-started.pt-BR.mdx, pages/docs/meta.pt-BR.json, pages/docs/middleware.pt-BR.md, pages/docs/mutation.pt-BR.md, pages/docs/options.pt-BR.mdx, pages/docs/pagination.pt-BR.mdx, pages/docs/prefetching.pt-BR.md, pages/docs/revalidation.pt-BR.mdx, pages/docs/suspense.pt-BR.mdx, pages/docs/typescript.pt-BR.mdx, pages/docs/with-nextjs.pt-BR.md, pages/index.pt-BR.mdx, theme.config.js
Correcting grammatical and typing errors in Brazilian Portuguese documentation, also improving the translations of code examples.
=> doc: fix portuguese typos

public/favicon/site.webmanifest
- Updates `icon_src` and adds `start_url` in webmanifest
=> update icon_src and add start_url in webmanifest.json

pages/docs/typescript.en-US.mdx, pages/docs/typescript.es-ES.mdx, pages/docs/typescript.ja.mdx, pages/docs/typescript.ko.mdx, pages/docs/typescript.pt-BR.mdx, pages/docs/typescript.ru.mdx, pages/docs/typescript.zh-CN.mdx
=> Fix order of generic types on Fetcher

pages/docs/mutation.zh-CN.md
https://github.com/vercel/swr-site/issues/319
=> fix: fix optimistic updates demo in zh-CN

pages/docs/advanced/cache.ko.mdx, pages/docs/advanced/react-native.ko.mdx, pages/docs/arguments.ko.md, pages/docs/global-configuration.ko.md, pages/docs/middleware.ko.md, pages/docs/mutation.ko.md, pages/docs/typescript.ko.mdx
=> doc: update doc for ko

pages/docs/revalidation.en-US.mdx
=> Fix typo in revalidation.en-US.mdx

pages/docs/advanced/devtools.en-US.mdx, pages/docs/advanced/devtools.es-ES.mdx, pages/docs/advanced/devtools.ja.mdx, pages/docs/advanced/devtools.ko.mdx, pages/docs/advanced/devtools.pt-BR.mdx, pages/docs/advanced/devtools.ru.mdx, pages/docs/advanced/devtools.zh-CN.mdx, pages/docs/advanced/meta.en-US.json, pages/docs/advanced/meta.es-ES.json, pages/docs/advanced/meta.ja.json, pages/docs/advanced/meta.ko.json, pages/docs/advanced/meta.pt-BR.json, pages/docs/advanced/meta.ru.json, pages/docs/advanced/meta.zh-CN.json
This PR adds a new page for SWRDevTools in the v2 documentation.
=>  docs: add DevTools page in v2

pages/docs/mutation.en-US.md, pages/docs/mutation.es-ES.md, pages/docs/mutation.ja.md, pages/docs/mutation.ko.md, pages/docs/mutation.pt-BR.md, pages/docs/mutation.ru.md, pages/docs/mutation.zh-CN.md
=> Fix a typo(full-width space) in code

pages/docs/suspense.en-US.mdx, pages/docs/suspense.es-ES.mdx, pages/docs/suspense.ja.mdx, pages/docs/suspense.ko.mdx, pages/docs/suspense.pt-BR.mdx, pages/docs/suspense.ru.mdx, pages/docs/suspense.zh-CN.mdx
This adds Suspense support in SWR v2 and React v18. I've updated the notes for Suspense in React v18 and added a note for SWR v2 with SSR. This is based on the release note.
https://github.com/vercel/swr/releases/tag/2.0.0-beta.3
=>  docs: add notes for Suspense on SSR and React v18 in SWR v2

pages/docs/pagination.ru.mdx
Hi there! 👋 
Detected a small typo in Russian docs
=> Fix typo: загразки -> загрузки

pages/blog/swr-v2.en-US.mdx
=> use link for codesandbox example

pages/docs/mutation.en-US.md, pages/docs/mutation.es-ES.md, pages/docs/mutation.ja.md, pages/docs/mutation.ko.md, pages/docs/mutation.pt-BR.md, pages/docs/mutation.ru.md, pages/docs/mutation.zh-CN.md
Adding description and example for https://github.com/vercel/swr/pull/2242
=> Add functional rollbackOnError description

pages/blog/swr-v2.en-US.mdx, pages/blog/swr-v2.es-ES.mdx, pages/blog/swr-v2.ja.mdx, pages/blog/swr-v2.ko.mdx, pages/blog/swr-v2.pt-BR.mdx, pages/blog/swr-v2.ru.mdx, pages/blog/swr-v2.zh-CN.mdx
=> Fix case for section title

pages/blog/swr-v2.en-US.mdx, pages/blog/swr-v2.es-ES.mdx, pages/blog/swr-v2.ja.mdx, pages/blog/swr-v2.ko.mdx, pages/blog/swr-v2.pt-BR.mdx, pages/blog/swr-v2.ru.mdx, pages/blog/swr-v2.zh-CN.mdx
=> Update card and description for the v2 blog post

pages/blog/swr-v2.ja.mdx
I've translated the description of v2 blog into Japanese
=> docs: translate the description of v2 blog into Japanese

pages/blog/swr-v2.en-US.mdx, pages/blog/swr-v2.es-ES.mdx, pages/blog/swr-v2.ko.mdx, pages/blog/swr-v2.pt-BR.mdx, pages/blog/swr-v2.zh-CN.mdx
Fixing typo in blog overview page
=> Fix blog SWR 2 description typo

pages/docs/advanced/react-native.es-ES.mdx
-Update `react-native` for spanish lenguage
I have added the **spanish version of react-native**.
=> Adding react-native spanish translation

pages/docs/mutation.zh-CN.md
=> docs: translate mutation to chinese

pages/docs/suspense.zh-CN.mdx
=> feat: add suspense chinese translation

pages/blog/meta.zh-CN.json, pages/blog/swr-v2.zh-CN.mdx
=> docs: translate swr v2 blog to chinese

pages/docs/api.zh-CN.mdx
=> docs: translate api to chinese

pages/docs/pagination.en-US.mdx, pages/docs/pagination.es-ES.mdx, pages/docs/pagination.ja.mdx, pages/docs/pagination.ko.mdx, pages/docs/pagination.pt-BR.mdx, pages/docs/pagination.ru.mdx, pages/docs/pagination.zh-CN.mdx
=> add a section for global mutate with useSWRInfinite

pages/docs/advanced/devtools.pt-BR.mdx, pages/docs/advanced/meta.pt-BR.json, pages/docs/advanced/understanding.pt-BR.mdx, pages/docs/suspense.pt-BR.mdx
=> Increment Brazilian Portuguese docs

pages/docs/advanced/understanding.ja.mdx
=> delete unnecessary asterisk

pages/docs/mutation.en-US.md
Just fixing a typo I found while perusing the docs! Thanks for this fantastic project 🥳
=> fix: typo on useMutation docs

theme.config.js
I have added spanish transalations on the theme config, search placeholder and table of contents title translation
=> doc:Add Spanish translations, search placeholder and toc title

pages/docs/advanced/cache.pt-BR.mdx, pages/docs/arguments.pt-BR.md, pages/docs/getting-started.pt-BR.mdx, pages/docs/mutation.pt-BR.md, pages/docs/pagination.pt-BR.mdx, pages/docs/suspense.pt-BR.mdx
Full translation of Mutations to Brazilian Portuguese, also incrementing translations to Arguments and fixing a typo in Suspense.
=> Improve Brazilian Portuguese translation coverage

theme.config.js
This PR updates some `theme.config.js` constants for Brazilian Portuguese.
=> Update pt-BR theme constants

pages/docs/_meta.en-US.json, pages/docs/_meta.es-ES.json, pages/docs/_meta.ja.json, pages/docs/_meta.ko.json, pages/docs/_meta.pt-BR.json, pages/docs/_meta.ru.json, pages/docs/_meta.zh-CN.json, pages/docs/subscription.en-US.mdx, pages/docs/subscription.es-ES.mdx, pages/docs/subscription.ja.mdx, pages/docs/subscription.ko.mdx, pages/docs/subscription.pt-BR.mdx, pages/docs/subscription.ru.mdx, pages/docs/subscription.zh-CN.mdx, pages/examples/_meta.en-US.json, pages/examples/_meta.es-ES.json, pages/examples/_meta.ja.json, pages/examples/_meta.ko.json, pages/examples/_meta.pt-BR.json, pages/examples/_meta.ru.json, pages/examples/_meta.zh-CN.json, pages/examples/subscription.en-US.mdx, pages/examples/subscription.es-ES.mdx, pages/examples/subscription.ja.mdx, pages/examples/subscription.ko.mdx, pages/examples/subscription.pt-BR.mdx, pages/examples/subscription.ru.mdx, pages/examples/subscription.zh-CN.mdx
Resolves #442 
Adding subscription doc
=> docs: subscription

pages/docs/pagination.en-US.mdx, pages/docs/pagination.es-ES.mdx, pages/docs/pagination.ja.mdx, pages/docs/pagination.ko.mdx, pages/docs/pagination.pt-BR.mdx, pages/docs/pagination.ru.mdx, pages/docs/pagination.zh-CN.mdx
fixes #443
PR: https://github.com/vercel/swr/pull/2404
=> docs: add parallel option for useSWRInfinite

pages/docs/pagination.ru.mdx
=> docs: russian translation for useSWRInfinite parallel option

pages/docs/subscription.ko.mdx
Add Korean translation of "subscription".
=> docs:Add korean translation of "subscription"

pages/docs/_meta.ru.json, pages/docs/subscription.ru.mdx
Re-opened #448 as it wasn't merged in #447 before merging to main
=> docs: russian translation for subscription

pages/blog/_meta.pt-BR.json, pages/blog/swr-v2.pt-BR.mdx, pages/docs/_meta.pt-BR.json, pages/docs/global-configuration.pt-BR.mdx, pages/docs/pagination.pt-BR.mdx, pages/docs/subscription.pt-BR.mdx, translations/text.js
- Translated Announcing SWR 2.0 blogpost
- Translated Nesting Configurations
- Translated `useSWRSubscription` parallel related docs and meta labels
- Translated new Subscription page
=> docs: Updating Portuguese documentation

pages/docs/_meta.ja.json, pages/docs/pagination.ja.mdx, pages/docs/subscription.ja.mdx
I've synced the Japanese translation.
=> docs: sync Japanese translation

pages/docs/mutation.ko.mdx
Add korean translation of "mutate"
=> docs: Add korean translation of "mutate"

pages/docs/subscription.en-US.mdx, pages/docs/subscription.es-ES.mdx, pages/docs/subscription.ja.mdx, pages/docs/subscription.ko.mdx, pages/docs/subscription.pt-BR.mdx, pages/docs/subscription.ru.mdx, pages/docs/subscription.zh-CN.mdx
=> Clarify args section of subscription

components/use-locales-map.js
* Fixes the undefined structureClone introduced in #465 , since the node runtime is still using v16 it doesn't have it globally.
* Remove unnecessary exports
=> Fix undefined structureClone

pages/docs/subscription.ru.mdx
=> docs: russian translation for clarified args section of subscription

pages/docs/_meta.zh-CN.json, pages/docs/subscription.en-US.mdx, pages/docs/subscription.es-ES.mdx, pages/docs/subscription.ja.mdx, pages/docs/subscription.ko.mdx, pages/docs/subscription.pt-BR.mdx, pages/docs/subscription.ru.mdx, pages/docs/subscription.zh-CN.mdx, pages/docs/typescript.en-US.mdx, pages/docs/typescript.es-ES.mdx, pages/docs/typescript.ja.mdx, pages/docs/typescript.ko.mdx, pages/docs/typescript.pt-BR.mdx, pages/docs/typescript.ru.mdx, pages/docs/typescript.zh-CN.mdx
=> improve subscription docs

pages/docs/api.zh-CN.mdx
=> docs: update chinese translation

pages/docs/subscription.en-US.mdx, pages/docs/subscription.es-ES.mdx, pages/docs/subscription.ja.mdx, pages/docs/subscription.ko.mdx, pages/docs/subscription.pt-BR.mdx, pages/docs/subscription.ru.mdx, pages/docs/subscription.zh-CN.mdx
ref: https://github.com/vercel/swr/pull/2551
=> update subscription usage

pages/docs/typescript.en-US.mdx
=> Fix ‘manually’ typo and remove extra space

theme.config.js, translations/text.js
=> Added translation for git timestamp

pages/docs/typescript.en-US.mdx, pages/docs/typescript.es-ES.mdx, pages/docs/typescript.ja.mdx, pages/docs/typescript.ko.mdx, pages/docs/typescript.pt-BR.mdx, pages/docs/typescript.ru.mdx, pages/docs/typescript.zh-CN.mdx
=> fix: invalid syntax in typescript example

pages/docs/typescript.ja.mdx
=> fix: typo in typescript.ja.mdx

pages/docs/global-configuration.en-US.mdx
=> Typo Fix: Update global-configuration.en-US.mdx

pages/docs/api.ja.mdx
=> Translate `details` into Japanese

pages/docs/with-nextjs.en-US.mdx, pages/docs/with-nextjs.es-ES.mdx, pages/docs/with-nextjs.fr-FR.mdx, pages/docs/with-nextjs.ja.mdx, pages/docs/with-nextjs.ko.mdx, pages/docs/with-nextjs.pt-BR.mdx, pages/docs/with-nextjs.ru.mdx, pages/docs/with-nextjs.zh-CN.mdx
=> add RSC docs

pages/docs/with-nextjs.en-US.mdx, pages/docs/with-nextjs.es-ES.mdx, pages/docs/with-nextjs.fr-FR.mdx, pages/docs/with-nextjs.ja.mdx, pages/docs/with-nextjs.ko.mdx, pages/docs/with-nextjs.pt-BR.mdx, pages/docs/with-nextjs.ru.mdx, pages/docs/with-nextjs.zh-CN.mdx
=> Polish rsc docs

pages/index.ko.mdx
`스태일`, `재검증` -> `stale`, `revalidate` (no translate)
SSR / ISR / SSG `support` -> `지원`
TypeScript `준비` -> `지원`
=> docs: Improves awkward translation

pages/docs/mutation.en-US.mdx, pages/docs/mutation.es-ES.mdx, pages/docs/mutation.fr-FR.mdx, pages/docs/mutation.ja.mdx, pages/docs/mutation.ko.mdx, pages/docs/mutation.pt-BR.mdx, pages/docs/mutation.ru.mdx, pages/docs/mutation.zh-CN.mdx
=> Fix duplicate section IDs

pages/docs/with-nextjs.ru.mdx
=> docs: russian translation for with-nextjs.ru.mdx

pages/docs/subscription.ru.mdx
Fix typo and full translate of the `subscription.ru.mdx` page.
=> Fix typo & full translate subscription.ru.mdx

pages/docs/_meta.pt-BR.json, pages/docs/conditional-fetching.pt-BR.mdx, pages/docs/mutation.pt-BR.mdx, pages/docs/pagination.pt-BR.mdx, pages/docs/prefetching.pt-BR.mdx, pages/docs/revalidation.pt-BR.mdx, pages/docs/subscription.pt-BR.mdx, pages/docs/with-nextjs.pt-BR.mdx
Updating contents from many pages, also changing some already done translations and terminologies:
- Prefetching page
- Conditional fetching
- Mutation page
- Pagination page
- Revalidation page
- Subscription page
- With Next.js page
=> Update Brazilian Portuguese contents

pages/index.ja.mdx
I Update return value description in [Index page](https://swr.vercel.app/).
I think this example using data, isLoading and error.
However, isLoading is missing from the description.
So I add isLoading in ja.
=> docs: Update useSWR return value descriptions

pages/docs/api.es-ES.mdx
Translate a text that was still in English.
=> chore: Update api.es-ES.mdx

pages/docs/advanced/understanding.zh-CN.mdx
=> docs: correct typo in docs/advanced/understanding

pages/docs/revalidation.ru.mdx, pages/docs/typescript.ru.mdx
=> Russian translation for revalidation.mdx and typescript.mdx

pages/docs/advanced/understanding.zh-CN.mdx
=> docs: add missing word `求` in docs

package.json, pnpm-lock.yaml
* Bump nextjs to v14
* Bump nextra to v2 latest
* Bump nodejs to v20 on deployment
=> upgrade nextjs to 14

pages/docs/mutation.zh-CN.mdx
=> docs: update Chinese translation for mutation options description

pages/docs/pagination.en-US.mdx, pages/docs/pagination.es-ES.mdx, pages/docs/pagination.fr-FR.mdx, pages/docs/pagination.ja.mdx, pages/docs/pagination.ko.mdx, pages/docs/pagination.zh-CN.mdx
update links related to React Hook rules
=> update rules of hooks links

pages/docs/suspense.en-US.mdx, pages/docs/suspense.es-ES.mdx, pages/docs/suspense.fr-FR.mdx, pages/docs/suspense.ja.mdx, pages/docs/suspense.ko.mdx, pages/docs/suspense.pt-BR.mdx, pages/docs/suspense.ru.mdx, pages/docs/suspense.zh-CN.mdx
Add back suspense header that was removed by mistake in https://github.com/vercel/swr-site/pull/611 😅
=> Add suspense header

pages/docs/pagination.zh-CN.mdx
docs: zh-CN translation in pages/docs/pagination.zh-CN.mdx
=> docs: zh-CN translation in pages/docs/pagination.zh-CN.mdx

pages/docs/subscription.es-ES.mdx
Docs: es-ES translation in pages/docs/subscription.es-ES.mdx
=> Docs: es-ES translation in pages/docs/subscription.es-ES.mdx
